name: 🐞 apko bug report
description: File a bug report
title: "[apko bug report]: "
labels: ["bug", "triage"]
assignees:
  - afeddersen
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file an issue for apko!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Please describe the issue.
      value: ""
    validations:
      required: true
  - type: dropdown
    id: packages
    attributes:
      label: Packages
      description: What is the distro? 
      options:
        - alpine-amd64
        - alpine-base-rootless
        - alpine-slim
        - nginx-rootless
        - nginx
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What is your favorite browser?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
