name: Add bugs to demo project

on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write 

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/afeddersen/projects/1/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug, needs-triage
          label-operator: OR
